"""Cover art: square, RGB, inside Apple's pixel window, under the byte target.

The byte target is the soft one — it comes from hosting-provider documentation
rather than Apple, whose own spec page serves nothing to a fetch. So the
behaviour worth pinning is not "512 KB exactly" but the decision the builder
makes when it cannot reach the budget: step quality down, then fall back to the
source's native size rather than keep crushing an upscale.
"""

from __future__ import annotations

import pytest
from PIL import Image

from dr2_podcast.publish.artwork import MIN_EDGE, ArtworkError, build_artwork, describe_artwork


def _flat_square(path, edge: int = 1536, mode: str = "RGB"):
    Image.new(mode, (edge, edge), (200, 40, 40)).save(path)
    return path


def _noisy_square(path, edge: int = 1536):
    """Detail JPEG cannot compress away — forces the quality ladder down.

    Generated by multiplication rather than `random` so the fixture is bit-identical
    on every run: a size-sensitive test whose input changes per run is a flake.
    """
    image = Image.new("RGB", (edge, edge))
    image.putdata([((i * 2654435761) % 256, (i * 40503) % 256, (i * 7919) % 256) for i in range(edge * edge)])
    image.save(path)
    return path


def _measure(source, probe, *, edge: int) -> int:
    """Bytes this source produces at `edge`, using the builder's own settings."""
    return build_artwork(source, probe, edge=edge, max_bytes=1 << 30)[1]


def test_a_compressible_source_reaches_the_requested_edge(tmp_path):
    source = _flat_square(tmp_path / "logo.png", edge=1536)
    edge, size = build_artwork(source, tmp_path / "artwork.jpg", edge=3000)
    fmt, dimensions, mode, actual = describe_artwork(tmp_path / "artwork.jpg")

    assert edge == 3000
    assert (fmt, dimensions, mode) == ("JPEG", (3000, 3000), "RGB")
    assert actual == size <= 512 * 1024


def test_an_upscale_that_will_not_fit_falls_back_to_the_native_size(tmp_path):
    """Native 1536 at good quality beats a 3000px upscale crushed to fit.

    The budget is derived from what this source actually compresses to rather
    than hardcoded, so the test pins the *decision* — fall back, don't keep
    crushing — and not a JPEG size that depends on the Pillow build.
    """
    source = _noisy_square(tmp_path / "logo.png", edge=1536)
    native = _measure(source, tmp_path / "probe_native.jpg", edge=1536)
    upscaled = _measure(source, tmp_path / "probe_3000.jpg", edge=3000)
    assert native < upscaled, "fixture assumption: the upscale is the larger file"
    budget = (native + upscaled) // 2

    edge, size = build_artwork(source, tmp_path / "artwork.jpg", edge=3000, max_bytes=budget)

    assert edge == 1536
    assert size <= budget
    assert describe_artwork(tmp_path / "artwork.jpg")[1] == (1536, 1536)


def test_a_source_that_cannot_fit_at_any_size_is_refused_and_leaves_nothing(tmp_path):
    source = _noisy_square(tmp_path / "logo.png", edge=1536)
    target = tmp_path / "artwork.jpg"
    with pytest.raises(ArtworkError, match="could not get"):
        build_artwork(source, target, edge=3000, max_bytes=1000)
    # No half-compliant file left behind for `stage` to pick up and ship.
    assert not target.exists()


def test_a_non_square_source_is_refused(tmp_path):
    """`Logo_original_backup.png` is 2816x1536 — Apple requires square art."""
    banner = tmp_path / "banner.png"
    Image.new("RGB", (2816, 1536), (10, 10, 10)).save(banner)
    with pytest.raises(ArtworkError, match="not square"):
        build_artwork(banner, tmp_path / "artwork.jpg")


def test_a_source_below_apples_minimum_is_refused(tmp_path):
    small = _flat_square(tmp_path / "small.png", edge=MIN_EDGE - 1)
    with pytest.raises(ArtworkError, match="minimum"):
        build_artwork(small, tmp_path / "artwork.jpg")


def test_rgba_is_flattened_to_rgb(tmp_path):
    """Apple requires RGB; an alpha channel survives a naive copy."""
    source = _flat_square(tmp_path / "logo.png", edge=1536, mode="RGBA")
    build_artwork(source, tmp_path / "artwork.jpg")
    assert describe_artwork(tmp_path / "artwork.jpg")[2] == "RGB"


def test_a_missing_source_is_refused(tmp_path):
    with pytest.raises(ArtworkError, match="no such image"):
        build_artwork(tmp_path / "nope.png", tmp_path / "artwork.jpg")
